apiVersion: v1
kind: Service
metadata:
  name: edge
  namespace: default
  labels:
    tier: streaming
spec:
  type: LoadBalancer
  ports:
    - name: edge-output-playlists
      port: 80
      targetPort: 8090
      protocol: "TCP"

    - name: edge-output-webrtc-signal
      port: 3334
      targetPort: 3334
      protocol: "TCP"

    - name: edge-output-webrtc-tcp-relay
      port: 3479
      targetPort: 3479
      protocol: "TCP"

  selector:
    app: edge
# Linode disallows having UDP & TCP load balancers in same cluster
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: webrtc-ice
#   namespace: default
#   labels:
#     tier: streaming
# spec:
#   type: LoadBalancer
#   ports:
#     - name: edge-output-webrtc-ice-0
#       port: 10000
#       targetPort: 10000
#       protocol: "UDP"
#     - name: edge-output-webrtc-ice-1
#       port: 10001
#       targetPort: 10001
#       protocol: "UDP"
#     - name: edge-output-webrtc-ice-2
#       port: 10002
#       targetPort: 10002
#       protocol: "UDP"
#     - name: edge-output-webrtc-ice-3
#       port: 10003
#       targetPort: 10003
#       protocol: "UDP"
#     - name: edge-output-webrtc-ice-4
#       port: 10004
#       targetPort: 10004
#       protocol: "UDP"
#     - name: edge-output-webrtc-ice-5
#       port: 10005
#       targetPort: 10005
#       protocol: "UDP"
#   selector:
#     app: edge
