apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: edge
  template:
    metadata:
      labels:
        app: edge
    spec:
      containers:
        - name: ome-edge
          image: syncronet/zome-ome
          command: ["/opt/ovenmediaengine/bin/OvenMediaEngine", "-c", "edge_conf"]
          env:
            - name: DEFAULT_ORIGIN_SERVER
              value: "10.128.142.175"
            - name: DEFAULT_ORIGIN_PORT
              value: "9000"
          ports:
            - name: webrtc-signal
              containerPort: 3334
              protocol: "TCP"
            - name: webrtc-relay
              containerPort: 3479
              protocol: "TCP"
            - name: webrtc-ice-0
              containerPort: 10000
              protocol: "UDP"
            - name: webrtc-ice-1
              containerPort: 10001
              protocol: "UDP"
            - name: webrtc-ice-2
              containerPort: 10002
              protocol: "UDP"
            - name: webrtc-ice-3
              containerPort: 10003
              protocol: "UDP"
            - name: webrtc-ice-4
              containerPort: 10004
              protocol: "UDP"
            - name: webrtc-ice-5
              containerPort: 10005
              protocol: "UDP"
            - name: playlists
              containerPort: 8090
              protocol: "TCP"
      imagePullSecrets:
        - name: regcred
