apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: origin
  namespace: default
spec:
  maxReplicas: 200
  minReplicas: 4
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: origin
  targetCPUUtilizationPercentage: 50